(let ((qt-dll-dir     "c:/Qt/5.15.2/msvc2019_64/bin/")
      (deploy-dir     "win32-deploy/")
      (qt-dll-list    '("Qt5Core.dll" "Qt5Widgets.dll" "Qt5Gui.dll"))
      (qt-plugins-dir "c:/Qt/5.15.2/msvc2019_64/plugins/")
      (qt-plugin-list '("imageformats" "styles" "platforms"))
      (release        "imageEditorApp/release/imageEditor.exe"))
  (when (not (file-exists-p deploy-dir))
      (make-directory deploy-dir))
  (mapcar (lambda (file) (copy-file (concat qt-dll-dir file) (concat deploy-dir file)) t) qt-dll-list)
  (mapcar (lambda (dir) (copy-directory (concat qt-plugins-dir dir) (concat deploy-dir dir))) qt-plugin-list)
  (copy-file release deploy-dir t))
